import { Community, CommunityPost } from "@/lib/types/groups"

export const DEFAULT_COMMUNITIES: Community[] = [
  {
    id: "comm-rt-02-pekauman",
    name: "RT 02 / RW 03 Kelurahan Pekauman",
    type: "RT_RW",
    category_label: "Wilayah RT/RW",
    description: "Komunitas resmi warga RT 02 / RW 03 Kelurahan Pekauman, Kecamatan Tegal Barat. Wadah koordinasi gotong royong, ronda malam, dan iuran lingkungan.",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    rw: "03",
    rt: "02",
    member_count: 86,
    post_count: 14,
    leader_name: "Bpk. Bambang Sutrisno",
    leader_role: "Ketua RT 02",
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-posyandu-melati",
    name: "Posyandu Melati 03 Pekauman",
    type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan kesehatan ibu, bayi balita, dan lansia. Penimbangan berkala, imunisasi, pemantauan status gizi stunting, dan PMT balita.",
    location: "Balai Warga RW 03, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    rw: "03",
    rt: "02",
    member_count: 124,
    post_count: 28,
    leader_name: "Ibu Hj. Siti Aminah",
    leader_role: "Ketua Kader Posyandu Melati",
    is_verified: true,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-paud-tunas-bangsa",
    name: "PAUD & KB Tunas Bangsa Pekauman",
    type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Pendidikan Anak Usia Dini & Kelompok Bermain ramah anak. Program stimulasi motorik, pendidikan karakter budi pekerti, dan parenting warga.",
    location: "Jl. Ki Gede Sebayu No. 12, Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    rw: "02",
    rt: "01",
    member_count: 65,
    post_count: 19,
    leader_name: "Ibu Rahayu Ningrum, S.Pd",
    leader_role: "Kepala Sekolah & Operator PAUD",
    is_verified: true,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-dinkes-tegal",
    name: "Dinas Kesehatan Kota Tegal",
    type: "OPD",
    category_label: "OPD/Dinas",
    description: "Kanal informasi resmi Dinas Kesehatan Kota Tegal. Program Universal Health Coverage (UHC), cegah stunting, jadwal vaksinasi, dan pencegahan DBD.",
    location: "Balai Kota Tegal / Jl. Proklamasi",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Mangkukusuman",
    member_count: 1420,
    post_count: 52,
    leader_name: "Tim Humas & Promkes Dinkes Kota Tegal",
    leader_role: "Admin OPD Terverifikasi",
    is_verified: true,
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-rw-05-kejambon",
    name: "Rukun Warga 05 Kejambon",
    type: "RT_RW",
    category_label: "Wilayah RT/RW",
    description: "Forum musyawarah antar RT di lingkungan RW 05 Kejambon, Tegal Timur. Agenda pembangunan infrastruktur, keamanan siskamling, dan bank sampah.",
    location: "Kec. Tegal Timur, Kel. Kejambon",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Kejambon",
    rw: "05",
    member_count: 156,
    post_count: 22,
    leader_name: "Bpk. H. Agus Riyadi",
    leader_role: "Ketua RW 05",
    is_verified: true,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-posyandu-mawar-randugunting",
    name: "Posyandu Mawar Sehat Randugunting",
    type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan terintegrasi posyandu balita & posbindu lansia di RW 04 Randugunting. Cek gula darah, tensi rutin, dan konsultasi gizi.",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    rw: "04",
    member_count: 98,
    post_count: 16,
    leader_name: "Ibu Nur Fatimah",
    leader_role: "Kader Kesehatan Posyandu Mawar",
    is_verified: true,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-paud-bintang-kecil",
    name: "KB Bintang Kecil Tegalsari",
    type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Pusat kegiatan belajar masyarakat (PKBM) & KB untuk anak pesisir dan maritim Tegalsari. Kurikulum merdeka belajar bermuatan lokal kelautan.",
    location: "Kec. Tegal Barat, Kel. Tegalsari",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Tegalsari",
    rw: "01",
    member_count: 54,
    post_count: 11,
    leader_name: "Ibu Dewi Lestari, S.Pd",
    leader_role: "Pengelola KB Bintang Kecil",
    is_verified: true,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "comm-disdikbud-tegal",
    name: "Dinas Pendidikan & Kebudayaan Kota Tegal",
    type: "OPD",
    category_label: "OPD/Dinas",
    description: "Informasi beasiswa daerah, penerimaan peserta didik baru (PPDB), akreditasi PAUD & sekolah, dan kegiatan pelestarian seni budaya Tegal.",
    location: "Jl. Kartini No. 4, Kota Tegal",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Mangkukusuman",
    member_count: 980,
    post_count: 37,
    leader_name: "Pusdatin Disdikbud Kota Tegal",
    leader_role: "Admin OPD Terverifikasi",
    is_verified: true,
    created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const DEFAULT_POSTS: Record<string, CommunityPost[]> = {
  "comm-rt-02-pekauman": [
    {
      id: "post-rt-1",
      community_id: "comm-rt-02-pekauman",
      content: "📢 PEMBERITAHUAN KERJA BAKTI WARGA:\nMenjelang musim penghujan, pengurus RT 02 / RW 03 mengundang seluruh kepala keluarga atau perwakilan warga untuk kerja bakti membersihkan drainase saluran air dan pemangkasan dahan pohon pada hari Minggu pukul 06.30 WIB di depan Pos Ronda. Disediakan sarapan & teh poci hangat.",
      category: "PENGUMUMAN",
      created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      author: {
        full_name: "Bpk. Bambang Sutrisno",
        active_role: "Ketua RT 02",
      },
      likes_count: 18,
      comments_count: 6,
    },
    {
      id: "post-rt-2",
      community_id: "comm-rt-02-pekauman",
      content: "Jadwal Petugas Ronda Malam minggu ini sudah ditempel di Pos Kamling RT 02. Mohon bagi warga yang berhalangan hadir agar dapat saling bertukar jadwal atau mengabari grup WA / aplikasi Jarimas. Terima kasih atas partisipasi menjaga keamanan lingkungan.",
      category: "KEGIATAN",
      created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      author: {
        full_name: "Slamet Riyanto",
        active_role: "Sie Keamanan RT 02",
      },
      likes_count: 12,
      comments_count: 3,
    },
  ],
  "comm-posyandu-melati": [
    {
      id: "post-pos-1",
      community_id: "comm-posyandu-melati",
      content: "👶 JADWAL PENIMBANGAN BALITA & VITAMIN A:\nPelayanan Posyandu Melati 03 bulan ini akan dilaksanakan:\n📅 Hari/Tgl: Sabtu ini\n⏰ Waktu: 08.00 - 11.00 WIB\n📍 Lokasi: Balai RW 03 Pekauman\n\nAgenda: Penimbangan berat badan, pengukuran tinggi badan, pemberian Vitamin A merah/biru, dan PMT (Pemberian Makanan Tambahan) bubur kacang hijau & telur. Jangan lupa membawa buku KIA!",
      category: "PENGUMUMAN",
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      author: {
        full_name: "Ibu Hj. Siti Aminah",
        active_role: "Kader Posyandu Melati",
      },
      likes_count: 24,
      comments_count: 8,
    },
    {
      id: "post-pos-2",
      community_id: "comm-posyandu-melati",
      content: "Alhamdulillah kegiatan pemeriksaan tensi darah dan senam lansia sehat tadi pagi berjalan lancar dengan dihadiri 38 peserta lansia RW 03. Terima kasih kepada tim Puskesmas Tegal Barat yang telah mendampingi.",
      category: "KEGIATAN",
      created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      author: {
        full_name: "Ibu Retno Wulandari",
        active_role: "Kader Posyandu Melati",
      },
      likes_count: 19,
      comments_count: 4,
    },
  ],
  "comm-paud-tunas-bangsa": [
    {
      id: "post-paud-1",
      community_id: "comm-paud-tunas-bangsa",
      content: "🎨 PENTAS SENI CILIK & PENGENALAN BUDAYA LOKAL TEGAL:\nDalam rangka menanamkan kecintaan budaya sejak dini, adik-adik kelompok bermain KB Tunas Bangsa akan menampilkan tari guci cilik dan lomba mewarnai motif batik tegalan. Wali murid dipersilakan hadir mendampingi pada hari Jumat pukul 08.30 WIB.",
      category: "KEGIATAN",
      created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      author: {
        full_name: "Ibu Rahayu Ningrum, S.Pd",
        active_role: "Operator PAUD Tunas Bangsa",
      },
      likes_count: 15,
      comments_count: 5,
    },
  ],
  "comm-dinkes-tegal": [
    {
      id: "post-dinkes-1",
      community_id: "comm-dinkes-tegal",
      content: "🏥 INFORMASI LAYANAN UHC (UNIVERSAL HEALTH COVERAGE) KOTA TEGAL:\nWarga Kota Tegal yang memiliki KTP Kota Tegal berhak mendapatkan akses layanan kesehatan gratis di Puskesmas dan RSUD rujukan. Pastikan NIK Anda terdaftar aktif. Bagi warga yang memerlukan pendampingan kepesertaan dapat berkonsultasi langsung di loket Puskesmas setempat.",
      category: "PENGUMUMAN",
      created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      author: {
        full_name: "Dinas Kesehatan Kota Tegal",
        active_role: "Admin OPD Terverifikasi",
      },
      likes_count: 67,
      comments_count: 14,
    },
  ],
}
