import { Community, CommunityPost } from "@/lib/types/groups"

export const DEFAULT_COMMUNITIES: Community[] = [
  // ============================================================================
  // RT / RW
  // ============================================================================
  {
    id: "d0000000-0000-4000-8000-000000000001",
    name: "Grup RT 02 / RW 03 Kel. Pekauman",
    type: "RT",
    community_type: "RT",
    category_label: "Wilayah RT/RW",
    description: "Forum resmi warga RT 02 / RW 03 Kelurahan Pekauman, Kecamatan Tegal Barat. Wadah koordinasi gotong royong, ronda malam, dan iuran lingkungan.",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    rw: "03",
    rt: "02",
    member_count: 86,
    post_count: 14,
    leader_name: "Bpk. Bambang Sutrisno",
    leader_role: "Ketua RT 02",
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ============================================================================
  // 1. POSYANDU RESMI KOTA TEGAL
  // ============================================================================

  // TEGAL BARAT - Pekauman
  {
    id: "d1000001-0000-4000-8000-000000000001",
    name: "Posyandu Tunas",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 112,
    post_count: 18,
    is_verified: true,
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000001-0000-4000-8000-000000000002",
    name: "Posyandu Duku",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 95,
    post_count: 10,
    is_verified: true,
    created_at: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000001-0000-4000-8000-000000000003",
    name: "Posyandu Garuda Pekauman",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 104,
    post_count: 14,
    is_verified: true,
    created_at: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000001-0000-4000-8000-000000000004",
    name: "Posyandu Belimbing",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 88,
    post_count: 8,
    is_verified: true,
    created_at: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000001-0000-4000-8000-000000000005",
    name: "Posyandu Jalak",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 79,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000001-0000-4000-8000-000000000006",
    name: "Posyandu Nanas",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 92,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000001-0000-4000-8000-000000000007",
    name: "Posyandu Delima Pekauman",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita & Kesehatan Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 85,
    post_count: 12,
    is_verified: true,
    created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // TEGAL BARAT - Pesurungan Kidul
  {
    id: "d1000002-0000-4000-8000-000000000001",
    name: "Posyandu Melati 1",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Pesurungan Kidul",
    location: "Kec. Tegal Barat, Kel. Pesurungan Kidul",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pesurungan Kidul",
    member_count: 94,
    post_count: 12,
    is_verified: true,
    created_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000002-0000-4000-8000-000000000002",
    name: "Posyandu Melati 2",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Pesurungan Kidul",
    location: "Kec. Tegal Barat, Kel. Pesurungan Kidul",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pesurungan Kidul",
    member_count: 82,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000002-0000-4000-8000-000000000003",
    name: "Posyandu Melati 3",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Pesurungan Kidul",
    location: "Kec. Tegal Barat, Kel. Pesurungan Kidul",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pesurungan Kidul",
    member_count: 76,
    post_count: 7,
    is_verified: true,
    created_at: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // TEGAL BARAT - Kemandungan
  {
    id: "d1000003-0000-4000-8000-000000000001",
    name: "Posyandu Cempaka Kemandungan",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kemandungan",
    location: "Kec. Tegal Barat, Kel. Kemandungan",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Kemandungan",
    member_count: 88,
    post_count: 10,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000003-0000-4000-8000-000000000002",
    name: "Posyandu Melati Kemandungan",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kemandungan",
    location: "Kec. Tegal Barat, Kel. Kemandungan",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Kemandungan",
    member_count: 91,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000003-0000-4000-8000-000000000003",
    name: "Posyandu Seruni Kemandungan",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kemandungan",
    location: "Kec. Tegal Barat, Kel. Kemandungan",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Kemandungan",
    member_count: 73,
    post_count: 6,
    is_verified: true,
    created_at: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // TEGAL BARAT - Debong Lor, Kraton, Tegalsari, Muarareja
  {
    id: "d1000004-0000-4000-8000-000000000001",
    name: "Posyandu Dahlia Debong Lor",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Debong Lor",
    location: "Kec. Tegal Barat, Kel. Debong Lor",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Debong Lor",
    member_count: 80,
    post_count: 8,
    is_verified: true,
    created_at: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000005-0000-4000-8000-000000000001",
    name: "Posyandu Mawar Kraton",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kraton",
    location: "Kec. Tegal Barat, Kel. Kraton",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Kraton",
    member_count: 85,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000006-0000-4000-8000-000000000001",
    name: "Posyandu Bahari Tegalsari",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Tegalsari",
    location: "Kec. Tegal Barat, Kel. Tegalsari",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Tegalsari",
    member_count: 98,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d1000007-0000-4000-8000-000000000001",
    name: "Posyandu Pantai Muarareja",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Muarareja",
    location: "Kec. Tegal Barat, Kel. Muarareja",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Muarareja",
    member_count: 77,
    post_count: 7,
    is_verified: true,
    created_at: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // TEGAL SELATAN - Randugunting
  {
    id: "d2000001-0000-4000-8000-000000000001",
    name: "Posyandu Ketilang",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 110,
    post_count: 16,
    is_verified: true,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000001-0000-4000-8000-000000000002",
    name: "Posyandu Nuri",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 102,
    post_count: 14,
    is_verified: true,
    created_at: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000001-0000-4000-8000-000000000003",
    name: "Posyandu Gelatik",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 98,
    post_count: 12,
    is_verified: true,
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000001-0000-4000-8000-000000000004",
    name: "Posyandu Rajawali",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 115,
    post_count: 19,
    is_verified: true,
    created_at: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000001-0000-4000-8000-000000000005",
    name: "Posyandu Garuda Randugunting",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 135,
    post_count: 24,
    is_verified: true,
    created_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000001-0000-4000-8000-000000000006",
    name: "Posyandu Meliwis",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 89,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // TEGAL SELATAN - Kelurahan Lainnya
  {
    id: "d2000002-0000-4000-8000-000000000001",
    name: "Posyandu Melati Kalinyamat Wetan",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kalinyamat Wetan",
    location: "Kec. Tegal Selatan, Kel. Kalinyamat Wetan",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Kalinyamat Wetan",
    member_count: 84,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000003-0000-4000-8000-000000000001",
    name: "Posyandu Mawar Bandung",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Bandung",
    location: "Kec. Tegal Selatan, Kel. Bandung",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Bandung",
    member_count: 78,
    post_count: 8,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000004-0000-4000-8000-000000000001",
    name: "Posyandu Cempaka Debong Kidul",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Debong Kidul",
    location: "Kec. Tegal Selatan, Kel. Debong Kidul",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Debong Kidul",
    member_count: 82,
    post_count: 10,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000005-0000-4000-8000-000000000001",
    name: "Posyandu Dahlia Tunon",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Tunon",
    location: "Kec. Tegal Selatan, Kel. Tunon",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Tunon",
    member_count: 75,
    post_count: 7,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000006-0000-4000-8000-000000000001",
    name: "Posyandu Flamboyan Keturen",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Keturen",
    location: "Kec. Tegal Selatan, Kel. Keturen",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Keturen",
    member_count: 81,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000007-0000-4000-8000-000000000001",
    name: "Posyandu Melati Debong Kulon",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Debong Kulon",
    location: "Kec. Tegal Selatan, Kel. Debong Kulon",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Debong Kulon",
    member_count: 79,
    post_count: 8,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d2000008-0000-4000-8000-000000000001",
    name: "Posyandu Anggrek Debong Tengah",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Debong Tengah",
    location: "Kec. Tegal Selatan, Kel. Debong Tengah",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Debong Tengah",
    member_count: 86,
    post_count: 10,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // TEGAL TIMUR - Kejambon
  {
    id: "d3000001-0000-4000-8000-000000000001",
    name: "Posyandu Kamboja 1",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kejambon",
    location: "Kec. Tegal Timur, Kel. Kejambon",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Kejambon",
    member_count: 88,
    post_count: 15,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3000001-0000-4000-8000-000000000002",
    name: "Posyandu Kamboja 2",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kejambon",
    location: "Kec. Tegal Timur, Kel. Kejambon",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Kejambon",
    member_count: 75,
    post_count: 8,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3000002-0000-4000-8000-000000000001",
    name: "Posyandu Aster Slerok",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Slerok",
    location: "Kec. Tegal Timur, Kel. Slerok",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Slerok",
    member_count: 90,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3000003-0000-4000-8000-000000000001",
    name: "Posyandu Teratai Panggung",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Panggung",
    location: "Kec. Tegal Timur, Kel. Panggung",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Panggung",
    member_count: 94,
    post_count: 12,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3000004-0000-4000-8000-000000000001",
    name: "Posyandu Bougenville Mangkukusuman",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Mangkukusuman",
    location: "Kec. Tegal Timur, Kel. Mangkukusuman",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Mangkukusuman",
    member_count: 83,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d3000005-0000-4000-8000-000000000001",
    name: "Posyandu Flamboyan Mintaragen",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Mintaragen",
    location: "Kec. Tegal Timur, Kel. Mintaragen",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Mintaragen",
    member_count: 87,
    post_count: 10,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // MARGADANA
  {
    id: "d4000001-0000-4000-8000-000000000001",
    name: "Posyandu Kenanga Margadana",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Margadana",
    location: "Kec. Margadana, Kel. Margadana",
    kecamatan_name: "Margadana",
    kelurahan_name: "Margadana",
    member_count: 92,
    post_count: 12,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4000002-0000-4000-8000-000000000001",
    name: "Posyandu Melati Kaligangsa",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kaligangsa",
    location: "Kec. Margadana, Kel. Kaligangsa",
    kecamatan_name: "Margadana",
    kelurahan_name: "Kaligangsa",
    member_count: 85,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4000003-0000-4000-8000-000000000001",
    name: "Posyandu Anggrek Krandon",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Krandon",
    location: "Kec. Margadana, Kel. Krandon",
    kecamatan_name: "Margadana",
    kelurahan_name: "Krandon",
    member_count: 78,
    post_count: 8,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4000004-0000-4000-8000-000000000001",
    name: "Posyandu Cempaka Cabawan",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Cabawan",
    location: "Kec. Margadana, Kel. Cabawan",
    kecamatan_name: "Margadana",
    kelurahan_name: "Cabawan",
    member_count: 74,
    post_count: 6,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4000005-0000-4000-8000-000000000001",
    name: "Posyandu Dahlia Kalinyamat Kulon",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Kalinyamat Kulon",
    location: "Kec. Margadana, Kel. Kalinyamat Kulon",
    kecamatan_name: "Margadana",
    kelurahan_name: "Kalinyamat Kulon",
    member_count: 82,
    post_count: 10,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4000006-0000-4000-8000-000000000001",
    name: "Posyandu Teratai Sumurpanggang",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Sumurpanggang",
    location: "Kec. Margadana, Kel. Sumurpanggang",
    kecamatan_name: "Margadana",
    kelurahan_name: "Sumurpanggang",
    member_count: 88,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "d4000007-0000-4000-8000-000000000001",
    name: "Posyandu Flamboyan Pesurungan Lor",
    type: "POSYANDU",
    community_type: "POSYANDU",
    category_label: "Posyandu",
    description: "Layanan Posyandu Balita Kelurahan Pesurungan Lor",
    location: "Kec. Margadana, Kel. Pesurungan Lor",
    kecamatan_name: "Margadana",
    kelurahan_name: "Pesurungan Lor",
    member_count: 80,
    post_count: 9,
    is_verified: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ============================================================================
  // 2. SATUAN PAUD, RA, PKBM, DAN SKB RESMI KOTA TEGAL
  // ============================================================================
  {
    id: "e1000001-0000-4000-8000-000000000001",
    name: "KB Al-Irsyad Pekauman",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Kelompok Bermain Islam Al-Irsyad Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 76,
    post_count: 21,
    is_verified: true,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e1000001-0000-4000-8000-000000000002",
    name: "RA At Taqwa Pekauman",
    type: "RA",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Raudhatul Athfal At Taqwa Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 58,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e1000001-0000-4000-8000-000000000003",
    name: "TK Aisyiyah Bustanul Athfal Pekauman",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Taman Kanak-Kanak ABA Kelurahan Pekauman",
    location: "Kec. Tegal Barat, Kel. Pekauman",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Pekauman",
    member_count: 65,
    post_count: 14,
    is_verified: true,
    created_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e2000001-0000-4000-8000-000000000001",
    name: "KB Bias Assalam Randugunting",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Kelompok Bermain Bina Anak Sholeh Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 62,
    post_count: 14,
    is_verified: true,
    created_at: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e2000001-0000-4000-8000-000000000002",
    name: "TK Pertiwi Randugunting",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Taman Kanak-Kanak Pertiwi Kelurahan Randugunting",
    location: "Kec. Tegal Selatan, Kel. Randugunting",
    kecamatan_name: "Tegal Selatan",
    kelurahan_name: "Randugunting",
    member_count: 70,
    post_count: 12,
    is_verified: true,
    created_at: new Date(Date.now() - 52 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e3000001-0000-4000-8000-000000000001",
    name: "RA Usamah 2 Mintaragen",
    type: "RA",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Raudhatul Athfal Usamah 2 Kelurahan Mintaragen",
    location: "Kec. Tegal Timur, Kel. Mintaragen",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Mintaragen",
    member_count: 80,
    post_count: 19,
    is_verified: true,
    created_at: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e3000001-0000-4000-8000-000000000002",
    name: "TK Pembina Mintaragen",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "TK Negeri Pembina Kecamatan Tegal Timur",
    location: "Kec. Tegal Timur, Kel. Mintaragen",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Mintaragen",
    member_count: 85,
    post_count: 16,
    is_verified: true,
    created_at: new Date(Date.now() - 68 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e1000002-0000-4000-8000-000000000001",
    name: "UPTD SPNF SKB Kota Tegal",
    type: "SKB",
    community_type: "PNF",
    category_label: "PAUD-PNF",
    description: "Sanggar Kegiatan Belajar Non-Formal Kota Tegal di Kraton",
    location: "Kec. Tegal Barat, Kel. Kraton",
    kecamatan_name: "Tegal Barat",
    kelurahan_name: "Kraton",
    member_count: 120,
    post_count: 28,
    is_verified: true,
    created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e3000002-0000-4000-8000-000000000001",
    name: "PKBM Sakila Kerti Panggung",
    type: "PKBM",
    community_type: "PNF",
    category_label: "PAUD-PNF",
    description: "Pusat Kegiatan Belajar Masyarakat Sakila Kerti Terminal Tegal",
    location: "Kec. Tegal Timur, Kel. Panggung",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Panggung",
    member_count: 95,
    post_count: 16,
    is_verified: true,
    created_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e3000003-0000-4000-8000-000000000001",
    name: "TK Muslimat NU Kejambon",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Taman Kanak-Kanak Muslimat NU Kejambon",
    location: "Kec. Tegal Timur, Kel. Kejambon",
    kecamatan_name: "Tegal Timur",
    kelurahan_name: "Kejambon",
    member_count: 68,
    post_count: 11,
    is_verified: true,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "e4000001-0000-4000-8000-000000000001",
    name: "KB Tunas Bangsa Margadana",
    type: "PAUD",
    community_type: "PAUD",
    category_label: "PAUD-PNF",
    description: "Kelompok Bermain Tunas Bangsa Margadana",
    location: "Kec. Margadana, Kel. Margadana",
    kecamatan_name: "Margadana",
    kelurahan_name: "Margadana",
    member_count: 72,
    post_count: 13,
    is_verified: true,
    created_at: new Date(Date.now() - 58 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_COMMUNITY_POSTS: Record<string, CommunityPost[]> = {
  "d0000000-0000-4000-8000-000000000001": [
    {
      id: "post-1",
      community_id: "d0000000-0000-4000-8000-000000000001",
      content: "📢 PEMBERITAHUAN KERJA BAKTI LINGKUNGAN:\nDiberitahukan kepada seluruh warga RT 02 / RW 03 Kelurahan Pekauman bahwa kerja bakti rutin pembersihan saluran air dan pemangkasan dahan pohon akan diadakan pada:\n🗓️ Hari: Minggu, 28 September\n⏰ Pukul: 07.00 WIB - selesai\n📍 Titik kumpul: Depan Pos Ronda RT 02\n\nMohon membawa peralatan kebersihan masing-masing. Konsumsi disediakan oleh ibu-ibu PKK.",
      user_id: "user-pak-rt",
      author_name: "Bambang Sutrisno",
      author_avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      author: {
        id: "user-pak-rt",
        full_name: "Bambang Sutrisno",
        avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
        active_role: "Ketua RT 02",
      },
    },
  ],
  "d1000001-0000-4000-8000-000000000001": [
    {
      id: "post-posyandu-1",
      community_id: "d1000001-0000-4000-8000-000000000001",
      content: "👶 JADWAL PENIMBANGAN BALITA & VITAMIN A:\nPelayanan Posyandu Tunas bulan ini akan dilaksanakan:\n📅 Hari/Tgl: Sabtu ini\n⏰ Waktu: 08.00 - 11.00 WIB\n📍 Lokasi: Balai Posyandu Pekauman\n\nAgenda: Penimbangan berat badan, pengukuran tinggi badan, pemberian Vitamin A merah/biru, dan PMT (Pemberian Makanan Tambahan) bubur kacang hijau & telur. Jangan lupa membawa buku KIA!",
      user_id: "user-kader-posyandu",
      author_name: "Bidan Sri Wahyuni",
      author_avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      author: {
        id: "user-kader-posyandu",
        full_name: "Bidan Sri Wahyuni",
        avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
        active_role: "Kader Posyandu",
      },
    },
  ],
}
