import { MarketplaceItem } from "@/lib/types/marketplace"

export const DEFAULT_MARKETPLACE_ITEMS: MarketplaceItem[] = [
  {
    id: "item-1",
    title: "Batik Tegal Tulis Motif Beras Wutah Asli",
    description: "Kain batik tulis khas pesisiran Tegal dengan motif klasik Beras Wutah. Bahan katun primissima halus, pewarnaan alami tahan lama. Ukuran 2.2m x 1.15m cocok untuk kemeja atau kain lilit.",
    price: 185000,
    category: "UMKM",
    category_label: "UMKM Lokal",
    kelurahan_code: "Pekauman",
    location: "Kel. Pekauman, Tegal Barat",
    condition: "BARU",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Ibu Sri Wahyuni (Batik Pekauman)",
      kelurahan_name: "Pekauman",
      phone_number: "081234567890",
    },
  },
  {
    id: "item-2",
    title: "Kupat Glabed & Sate Blengong Spesial Gurih",
    description: "Kupat Glabed kuah kuning kental gurih disajikan dengan kerupuk mie kuning dan sate blengong empuk khas Tegal. Siap antar wilayah Tegal Kota minimal order 3 porsi.",
    price: 25000,
    category: "KULINER",
    category_label: "Kuliner Tegal",
    kelurahan_code: "Mangkukusuman",
    location: "Kel. Mangkukusuman, Tegal Timur",
    condition: "BARU",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Warung Bu Nur Alun-alun",
      kelurahan_name: "Mangkukusuman",
      phone_number: "085678901234",
    },
  },
  {
    id: "item-3",
    title: "Jasa Servis & Cuci AC Rumah Bergaransi",
    description: "Layanan cuci AC 1/2 PK - 2 PK, tambah freon R32/R410, perbaikan modul dan kebocoran air. Teknisi warga lokal bersertifikat dan bergaransi 30 hari.",
    price: 65000,
    category: "JASA",
    category_label: "Jasa Warga",
    kelurahan_code: "Kraton",
    location: "Kel. Kraton, Tegal Barat",
    condition: "LAYANAN",
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Mas Agus Teknik",
      kelurahan_name: "Kraton",
      phone_number: "087812345678",
    },
  },
  {
    id: "item-4",
    title: "Sepeda Lipat Polygon Urbano 3 Mulus 95%",
    description: "Dijual sepeda lipat Polygon Urbano 3 warna hitam doff. Kondisi mulus jarang pakai, groupset Shimano 8 speed normal lancar, ban masih tebal. Nego tipis setelah cek unit di lokasi.",
    price: 1450000,
    category: "BEKAS",
    category_label: "Barang Bekas",
    kelurahan_code: "Kejambon",
    location: "Kel. Kejambon, Tegal Timur",
    condition: "BEKAS",
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Hendra Setiawan",
      kelurahan_name: "Kejambon",
      phone_number: "089612345678",
    },
  },
  {
    id: "item-5",
    title: "Pelatihan Keterampilan Menjahit & Desain Busana SPM",
    description: "Program Standar Pelayanan Minimal (SPM) peningkatan kapasitas ekonomi warga. Gratis untuk warga ber-KTP Kota Tegal. Disediakan modul, mesin jahit praktik, dan sertifikat kelulusan.",
    price: 0,
    category: "SPM",
    category_label: "Layanan SPM",
    kelurahan_code: "Debong Tengah",
    location: "Kel. Debong Tengah, Tegal Selatan",
    condition: "LAYANAN",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Pokja Pemberdayaan Warga SPM",
      kelurahan_name: "Debong Tengah",
      phone_number: "081398765432",
    },
  },
  {
    id: "item-6",
    title: "Paket Teh Poci Tegal Asli + Poci Tanah Liat & Gula Batu",
    description: "Satu set lengkap ritual Teh Poci khas Tegal: poci dan cangkir tanah liat asli Slawi/Tegal, 2 bungkus teh wangi melati cap Sintren/Dandang, dan 500gr gula batu kristal alami.",
    price: 45000,
    category: "UMKM",
    category_label: "UMKM Lokal",
    kelurahan_code: "Tegalsari",
    location: "Kel. Tegalsari, Tegal Barat",
    condition: "BARU",
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Oleh-oleh Poci Ibu Marto",
      kelurahan_name: "Tegalsari",
      phone_number: "082134567891",
    },
  },
  {
    id: "item-7",
    title: "Tahu Aci & Tahu Pletok Goreng Dadakan Khas Tegal (Isi 20)",
    description: "Tahu kuning khas Tegal dengan adonan aci bumbu kucai gurih kenyal dan renyah. Digoreng dadakan saat pesanan masuk, dilengkapi cabai rawit hijau segar.",
    price: 20000,
    category: "KULINER",
    category_label: "Kuliner Tegal",
    kelurahan_code: "Randugunting",
    location: "Kel. Randugunting, Tegal Selatan",
    condition: "BARU",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Tahu Aci Mas Dono",
      kelurahan_name: "Randugunting",
      phone_number: "085234567892",
    },
  },
  {
    id: "item-8",
    title: "Meja Belajar Kayu Jati Minimalis Kokoh Seken",
    description: "Meja belajar anak / kerja dari kayu jati asli. Ada 2 laci penyimpanan berkunci. Kondisi fisik 90% kokoh tanpa rayap, siap pakai.",
    price: 350000,
    category: "BEKAS",
    category_label: "Barang Bekas",
    kelurahan_code: "Margadana",
    location: "Kel. Margadana, Margadana",
    condition: "BEKAS",
    created_at: new Date(Date.now() - 52 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    seller: {
      full_name: "Bpk. Subur Margadana",
      kelurahan_name: "Margadana",
      phone_number: "087734567893",
    },
  },
]
